seedBase();ensureArrays();
var parentUser=JSON.parse(sessionStorage.getItem('afaq_current_parent')||'null');
if(!parentUser){alert('يجب تسجيل دخول ولي الأمر أولاً');location.href='../index.html'}
var children=getChildrenForParent(parentUser);
if(!children.length){alert('لم يتم العثور على طالب مرتبط بولي الأمر');location.href='../index.html'}
var student=children[0],current='home',messageBox='الوارد';
var nav=[['الرئيسية','home'],['اختيار الطالب','children'],['معلومات الطالب','studentInfo'],['مستوى الطالب','level'],['المواد والتقدم','subjects'],['النتائج','results'],['النتائج النهائية','finalGrades'],['الحضور والغياب','attendance'],['التنبيهات','alerts'],['تقرير شهري','monthlyReport'],['الإشعارات','notifications'],['التواصل','messages']];
function qs(x){return document.getElementById(x)}
function panel(t,d){return '<section class="panel"><h2>'+t+'</h2><p class="muted">'+(d||'')+'</p>'+childSwitcher()}
function childSwitcher(){var html='<div class="child-switch">';children.forEach(function(c){html+='<button class="btn '+(c.id===student.id?'active':'')+'" onclick="selectChild(&quot;'+c.id+'&quot;)">'+c.name+'</button>'});return html+'</div>'}
function selectChild(idv){student=children.find(function(c){return c.id===idv})||student;parentInfo.textContent=parentUser.name+' / الطالب الحالي: '+student.name;openSection(current)}
function acceptedSubjects(){var codes=getData('studentSubjects').filter(function(x){return x.studentId===student.id&&x.status==='accepted'}).map(function(x){return x.subjectCode});return getData('subjects').filter(function(s){return s.stage===student.stage&&codes.indexOf(s.code)!==-1})}
function drawSide(){var unread=parentUnreadNotifications(parentUser);parentSide.innerHTML='<h2>'+parentUser.name+'</h2>';nav.forEach(function(n){var b=document.createElement('button');b.className='nav'+(current===n[1]?' active':'');var badge=n[1]==='notifications'&&unread?'<span class="badge-count">'+unread+'</span>':'';b.innerHTML='<span>'+n[0]+badge+'</span><span>›</span>';b.onclick=function(){openSection(n[1])};parentSide.appendChild(b)})}
function openSection(s){current=s;drawSide();({home:showHome,children:showChildren,studentInfo:showStudentInfo,level:showLevel,subjects:showSubjects,results:showResults,finalGrades:showFinalGrades,attendance:showAttendance,alerts:showAlerts,monthlyReport:showMonthlyReport,notifications:showNotifications,messages:showMessages}[s]||showHome)()}
function showHome(){var pts=calcStudentPoints(student),alerts=buildAlerts();parentContent.innerHTML=panel('الرئيسية','متابعة مختصرة للطالب المحدد.')+'<div class="stats"><div class="stat"><h3>النقاط</h3><strong>'+pts+'</strong></div><div class="stat"><h3>المستوى</h3><strong>'+levelFromPoints(pts)+'</strong></div><div class="stat"><h3>المواد</h3><strong>'+acceptedSubjects().length+'</strong></div><div class="stat"><h3>تنبيهات</h3><strong>'+alerts.length+'</strong></div></div></section>'}
function showChildren(){var html=panel('اختيار الطالب','متابعة أكثر من طالب من نفس الحساب.')+'<div class="card-grid">';children.forEach(function(c){var p=calcStudentPoints(c);html+='<div class="data-card"><div class="student-avatar">🎓</div><h3>'+c.name+'</h3><p><span class="chip">'+c.stage+'</span></p><p><span class="chip">'+levelFromPoints(p)+'</span><span class="chip">'+p+' نقطة</span></p><button class="btn green" onclick="selectChild(&quot;'+c.id+'&quot;)">متابعة هذا الطالب</button></div>'});parentContent.innerHTML=html+'</div></section>'}
function showStudentInfo(){var exp=student.endDate&&new Date(student.endDate).getTime()<Date.now();parentContent.innerHTML=panel('معلومات الطالب','بيانات الطالب والاشتراك.')+'<div class="details-grid"><div class="detail-box"><b>اسم الطالب</b>'+student.name+'</div><div class="detail-box"><b>المرحلة</b>'+student.stage+'</div><div class="detail-box"><b>كود الطالب</b>'+student.code+'</div><div class="detail-box"><b>الهاتف</b>'+(student.phone||'—')+'</div><div class="detail-box"><b>حالة الحساب</b>'+(student.status||'—')+'</div><div class="detail-box"><b>الاشتراك</b>'+(exp?'منتهي':(student.subscriptionStatus||'—'))+'</div></div></section>'}
function showLevel(){var p=calcStudentPoints(student),board=buildHonorBoard(student.stage),rank=board.findIndex(function(x){return x.studentId===student.id})+1,r=monthlyStudentReport(student);parentContent.innerHTML=panel('مستوى الطالب','النقاط والمستوى والترتيب.')+'<div class="level-card"><h3 class="level-title">'+levelFromPoints(p)+'</h3><div class="points-big">'+p+' نقطة</div><p><span class="chip">الترتيب: '+(rank||'—')+'</span><span class="chip">اختبارات: '+r.attempts+'</span><span class="chip">واجبات: '+r.assignments+'</span><span class="chip">حضور: '+r.present+'</span></p></div></section>'}
function showSubjects(){var data=acceptedSubjects(),html=panel('المواد والتقدم','نسبة إنجاز الطالب في كل مادة.')+'<div class="card-grid">';if(!data.length)html+='<div class="empty">لا توجد مواد مقبول بها بعد.</div>';data.forEach(function(s){var pr=subjectProgressForStudent(student,s.code);html+='<div class="parent-subject"><div class="icon-big">'+(s.icon||'📘')+'</div><h3>'+s.name+'</h3><p class="muted">المدرس: '+(s.teacher||'غير محدد')+'</p><div class="progress-line"><div class="progress-fill" style="width:'+pr.percent+'%"></div></div><p><span class="chip">الإنجاز: '+pr.percent+'%</span><span class="chip">دروس: '+pr.lessons+'</span><span class="chip">واجبات: '+pr.submitted+'/'+pr.assignments+'</span><span class="chip">اختبارات: '+pr.attempts+'/'+pr.exams+'</span></p><button class="btn blue" onclick="messageTeacher(&quot;'+s.name+'&quot;,&quot;'+(s.teacher||'المدرس')+'&quot;)">مراسلة المدرس</button></div>'});parentContent.innerHTML=html+'</div></section>'}
function showResults(){var results=getData('results').filter(function(r){return r.studentName===student.name}),assignments=getData('assignmentSubmissions').filter(function(a){return a.studentId===student.id});var html=panel('النتائج','نتائج الاختبارات والواجبات.')+'<h3>الاختبارات</h3><div class="card-grid">';if(!results.length)html+='<div class="empty">لا توجد نتائج اختبارات.</div>';results.forEach(function(r){html+='<div class="data-card"><div class="icon-big">📊</div><h3>'+r.title+'</h3><p><span class="chip">'+r.subject+'</span></p><p class="final-grade">'+r.score+' / '+r.finalScore+'</p></div>'});html+='</div><h3>الواجبات</h3><div class="card-grid">';if(!assignments.length)html+='<div class="empty">لا توجد واجبات مصححة.</div>';assignments.forEach(function(a){html+='<div class="data-card"><div class="icon-big">📝</div><h3>'+a.assignmentTitle+'</h3><p><span class="chip">'+a.subject+'</span></p><p class="final-grade">'+(a.grade||'بانتظار التصحيح')+'</p></div>'});parentContent.innerHTML=html+'</div></section>'}
function showFinalGrades(){var finals=getData('finalGrades').filter(function(g){return g.studentName===student.name}),html=panel('النتائج النهائية','النتيجة النهائية لكل مادة.')+'<div class="card-grid">';if(!finals.length)html+='<div class="empty">لا توجد نتائج نهائية.</div>';finals.forEach(function(g){html+='<div class="data-card"><div class="icon-big">🎯</div><h3>'+g.subject+'</h3><p class="final-grade">'+g.grade+' / '+g.finalScore+'</p></div>'});parentContent.innerHTML=html+'</div></section>'}
function showAttendance(){var codes=acceptedSubjects().map(function(s){return s.code}),sessions=getData('attendance').filter(function(a){return codes.indexOf(a.subjectCode)!==-1}),records=getData('attendanceRecords').filter(function(r){return r.studentId===student.id}),present=records.filter(function(r){return r.status==='حاضر'}).length,absent=Math.max(0,sessions.length-present);var html=panel('الحضور والغياب','متابعة الحضور والغياب.')+'<div class="stats"><div class="stat"><h3>الحضور</h3><strong>'+present+'</strong></div><div class="stat"><h3>الغياب</h3><strong>'+absent+'</strong></div><div class="stat"><h3>الجلسات</h3><strong>'+sessions.length+'</strong></div></div></section>';parentContent.innerHTML=html}
function buildAlerts(){var alerts=[];if(student.endDate){var days=Math.ceil((new Date(student.endDate).getTime()-Date.now())/(1000*60*60*24));if(days<=7)alerts.push('اشتراك الطالب ينتهي قريباً');if(days<0)alerts.push('اشتراك الطالب منتهي')}getData('assignments').forEach(function(a){var accepted=isStudentAcceptedInSubject(student,a.subjectCode),sub=getData('assignmentSubmissions').find(function(s){return s.assignmentId===a.id&&s.studentId===student.id});if(accepted&&!sub)alerts.push('واجب غير محلول: '+a.title)});return alerts}
function showAlerts(){var alerts=buildAlerts(),html=panel('التنبيهات','تنبيهات مهمة تخص الطالب.')+'<div class="mini-list">';if(!alerts.length)html+='<div class="parent-good">لا توجد تنبيهات حالياً.</div>';alerts.forEach(function(a){html+='<div class="parent-alert">⚠️ '+a+'</div>'});parentContent.innerHTML=html+'</div></section>'}
function showMonthlyReport(){var r=monthlyStudentReport(student);parentContent.innerHTML=panel('تقرير شهري','ملخص شهري قابل للمراجعة.')+'<div class="report-box"><h3>'+student.name+'</h3><p><span class="chip">المستوى: '+r.level+'</span><span class="chip">النقاط: '+r.points+'</span></p><p><span class="chip">اختبارات: '+r.attempts+'</span><span class="chip">واجبات: '+r.assignments+'</span></p><p><span class="chip">حضور: '+r.present+'</span><span class="chip">غياب: '+r.absent+'</span></p></div></section>'}
function showNotifications(){var data=getVisibleNotificationsForParent(parentUser),html=panel('الإشعارات','تختفي الشارة بعد فتح هذا القسم.')+'<div class="card-grid">';if(!data.length)html+='<div class="empty">لا توجد إشعارات.</div>';data.forEach(function(n){html+='<div class="data-card"><div class="icon-big">🔔</div><h3>'+n.title+'</h3><p><span class="chip">'+(n.studentName||n.subject||n.target||'عام')+'</span></p><p class="muted">'+(n.body||'')+'</p></div>'});markParentNotificationsRead(parentUser);parentContent.innerHTML=html+'</div></section>';drawSide()}
function showMessages(){var all=getData('messages').filter(function(m){return m.from===parentUser.name||m.to===parentUser.name||m.studentName===student.name||m.to==='الإدارة'}),html=panel('التواصل','مراسلة المدرسين والإدارة وصندوق وارد كامل.')+'<div class="inbox-tabs"><button class="btn '+(messageBox==='الوارد'?'active':'')+'" onclick="setBox(&quot;الوارد&quot;)">الوارد</button><button class="btn '+(messageBox==='المرسل'?'active':'')+'" onclick="setBox(&quot;المرسل&quot;)">المرسل</button><button class="btn '+(messageBox==='الأرشيف'?'active':'')+'" onclick="setBox(&quot;الأرشيف&quot;)">الأرشيف</button><button class="btn green" onclick="messageAdmin()">رسالة إلى الإدارة</button></div><div class="card-grid">';var filtered=all.filter(function(m){return messageBox==='المرسل'?m.from===parentUser.name:messageBox==='الوارد'?m.to===parentUser.name:messageBox==='الأرشيف'?m.box==='الأرشيف':true});if(!filtered.length)html+='<div class="empty">لا توجد رسائل.</div>';filtered.forEach(function(m){html+='<div class="message-box"><h3>'+m.title+'</h3><p class="muted">من: '+m.from+' / إلى: '+m.to+'</p><p>'+m.body+'</p></div>'});parentContent.innerHTML=html+'</div></section>'}
function setBox(b){messageBox=b;showMessages()}
function messageTeacher(subject,teacherName){modalTitle.textContent='رسالة إلى مدرس '+subject;formFields.innerHTML='<div class="field"><label>إلى</label><input id="msgTo" value="'+teacherName+'"></div><div class="field"><label>العنوان</label><input id="msgTitle" value="استفسار بخصوص '+subject+'"></div><div class="field full"><label>الرسالة</label><textarea id="msgBody"></textarea></div>';parentModal.classList.add('active')}
function messageAdmin(){modalTitle.textContent='رسالة إلى الإدارة';formFields.innerHTML='<div class="field"><label>إلى</label><input id="msgTo" value="الإدارة"></div><div class="field"><label>العنوان</label><input id="msgTitle" value="استفسار من ولي الأمر"></div><div class="field full"><label>الرسالة</label><textarea id="msgBody"></textarea></div>';parentModal.classList.add('active')}
parentForm.onsubmit=function(e){e.preventDefault();var arr=getData('messages');arr.unshift({id:id(),from:parentUser.name,to:qs('msgTo').value,title:qs('msgTitle').value,body:qs('msgBody').value,box:'المرسل',studentId:student.id,studentName:student.name,createdAt:new Date().toLocaleString('ar-IQ')});setData('messages',arr);parentModal.classList.remove('active');showMessages()}
window.addEventListener('storage',function(e){if(e.key&&e.key.indexOf(P)===0){try{drawSide();openSection(current)}catch(err){}}})
parentInfo.textContent=parentUser.name+' / الطالب الحالي: '+student.name;drawSide();openSection('home');


// ===== v8.0.2 parent full live refresh =====
window.addEventListener('afaq:data-changed',function(e){
  if(e.detail&&['notifications','results','finalGrades','attendanceRecords','assignmentSubmissions','studentSubjects'].indexOf(e.detail.key)!==-1){
    try{drawSide(); if(current==='notifications')showNotifications(); else openSection(current);}catch(err){}
  }
});
