
import * as A from "./core.js";import {guard,shell,panel,card,showNotifications,updateBadge,statBox} from "./dashboard.js";
const user=guard("student");const nav=[{id:"home",title:"الرئيسية",icon:"🏠"},{id:"subjects",title:"المواد",icon:"📚"},{id:"lessons",title:"الدروس",icon:"📄"},{id:"assignments",title:"الواجبات",icon:"📝"},{id:"exams",title:"الاختبارات",icon:"🧪"},{id:"results",title:"النتائج",icon:"🏆"},{id:"leaderboard",title:"لوحة الشرف",icon:"⭐"},{id:"notifications",title:"الإشعارات",icon:"🔔"},{id:"messages",title:"الرسائل",icon:"✉️"}];let draw=shell("لوحة الطالب v10","student",user,nav);let current="home";
window.openSection=async id=>{current=id;draw(id);updateBadge("student",user);if(id==="home")home();if(id==="subjects")subjects();if(id==="lessons")showBy("lessons","الدروس");if(id==="assignments")assignments();if(id==="exams")exams();if(id==="results")results();if(id==="leaderboard")leaderboard();if(id==="notifications"){await showNotifications("student",user);updateBadge("student",user)}if(id==="messages")messages()}
function home(){let p=A.studentProfile(user);content.innerHTML=panel("مرحباً "+user.name,`المرحلة: ${user.stage}`)+`<div class="stats">${statBox("النقاط",p.points)}${statBox("المستوى",p.level)}${statBox("المواد",p.subjects.length)}${statBox("إشعارات",A.unreadCount("student",user))}</div>`}
function subjects(){let accepted=A.acceptedSubjects(user).map(s=>s.code);let subs=A.subjects(user.stage);content.innerHTML=panel("موادي الدراسية","لا يظهر كود المادة للطالب.")+`<div class="card-grid">${subs.map(s=>card(s.name,`<p>${s.teacher||"بانتظار مدرس"}</p><span class="chip">${accepted.includes(s.code)?"مقبول":"غير مقبول"}</span>`,accepted.includes(s.code)?`<button class="green">مفتوحة</button>`:`<button onclick="req('${s.id}')">إرسال طلب</button>`)).join("")||'<div class="empty">لا توجد مواد لهذه المرحلة</div>'}</div>`}
window.req=async idv=>{let sub=A.getData("subjects").find(s=>s.id===idv);await A.requestSubject(user,sub);alert("تم إرسال الطلب للمدرس");subjects()}
function allowed(){return A.acceptedSubjects(user).map(s=>s.code)}
function showBy(k,title){let codes=allowed();let arr=A.getData(k).filter(x=>codes.includes(x.subjectCode)&&x.status!=="مخفي");content.innerHTML=panel(title)+`<div class="card-grid">${arr.map(x=>card(x.title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<p class="muted">${x.subject}</p>`)).join("")||'<div class="empty">لا توجد بيانات</div>'}</div>`}
function assignments(){let codes=allowed();let arr=A.getData("assignments").filter(x=>codes.includes(x.subjectCode)&&x.status!=="مخفي");content.innerHTML=panel("الواجبات")+`<div class="card-grid">${arr.map(x=>{let sub=A.getData("assignmentSubmissions").find(s=>s.assignmentId===x.id&&s.studentId===user.id);return card(x.title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<span class="chip">${sub?("تم التسليم / "+(sub.grade||"بانتظار التصحيح")):"غير مسلم"}</span>`,sub?"":`<button onclick="submitAssign('${x.id}')">تسليم</button>`) }).join("")||'<div class="empty">لا توجد واجبات</div>'}</div>`}
window.submitAssign=async id=>{let a=A.getData("assignments").find(x=>x.id===id);let ans=prompt("اكتب حل الواجب أو رابط الحل");if(ans)await A.addItem("assignmentSubmissions",{assignmentId:id,assignmentTitle:a.title,studentId:user.id,studentCode:user.code,studentName:user.name,subject:a.subject,subjectCode:a.subjectCode,answer:ans,status:"بانتظار التصحيح",createdAt:A.now()});assignments()}
function exams(){let codes=allowed();let arr=A.getData("exams").filter(x=>codes.includes(x.subjectCode)&&x.status!=="مخفي");content.innerHTML=panel("الاختبارات")+`<div class="card-grid">${arr.map(e=>{let done=A.getData("examAttempts").find(a=>a.examId===e.id&&a.studentId===user.id);return card(e.title,`<p>عدد الأسئلة: ${(e.questions||[]).length}</p><span class="chip">${done?`درجتك ${done.score}/${done.total}`:"لم تحل"}</span>`,done?"":`<button onclick="takeExam('${e.id}')">بدء الاختبار</button>`) }).join("")||'<div class="empty">لا توجد اختبارات</div>'}</div>`}
window.takeExam=async id=>{let e=A.getData("exams").find(x=>x.id===id), answers={};(e.questions||[]).forEach((q,i)=>answers[i]=prompt(q.text));let res=A.createExamResult(e,user,answers);await A.addItem("examAttempts",res);await A.addItem("finalResults",{studentId:user.id,studentCode:user.code,studentName:user.name,subject:e.subject,score:res.score,grade:res.score,total:res.total,createdAt:A.now()});alert(`درجتك ${res.score}/${res.total}`);exams()}
function results(){let p=A.studentProfile(user);content.innerHTML=panel("النتائج")+`<div class="card-grid">${p.results.map(r=>card(r.subject||"نتيجة",`<strong>${r.score||r.grade}/${r.total||""}</strong>`)).join("")||'<div class="empty">لا توجد نتائج</div>'}</div>`}
function leaderboard(){let arr=A.leaderboard(user.stage);content.innerHTML=panel("لوحة الشرف")+`<div class="card-grid">${arr.map((s,i)=>`<div class="data-card rank-card"><div class="rank-no">#${i+1}</div><h3>${s.name}</h3><span class="chip">${s.level}</span><span class="chip">${s.points} نقطة</span></div>`).join("")}</div>`}
function messages(){content.innerHTML=panel("الرسائل")+`<button class="green" onclick="send()">إرسال رسالة</button>`}
window.send=async()=>{let body=prompt("اكتب الرسالة");if(body)await A.addItem("messages",{from:user.name,to:"admin",title:"رسالة طالب",body,studentId:user.id,studentName:user.name,createdAt:A.now()})}
A.onSync(()=>openSection(current));openSection("home");
