
import * as A from "./core.js";import {guard,shell,panel,card,showNotifications,updateBadge} from "./dashboard.js";
const user=guard("student");let nav=[{id:"home",title:"الرئيسية",icon:"🏠"},{id:"subjects",title:"المواد",icon:"📚"},{id:"lessons",title:"الدروس",icon:"📄"},{id:"assignments",title:"الواجبات",icon:"📝"},{id:"exams",title:"الاختبارات",icon:"🧪"},{id:"results",title:"النتائج",icon:"🏆"},{id:"notifications",title:"الإشعارات",icon:"🔔"},{id:"messages",title:"الرسائل",icon:"✉️"}];let draw=shell("لوحة الطالب","student",user,nav);let current="home";
window.openSection=async id=>{current=id;draw(id);updateBadge("student",user);if(id==="home")home();if(id==="subjects")subjects();if(id==="lessons")showBy("lessons","الدروس");if(id==="assignments")showBy("assignments","الواجبات");if(id==="exams")showBy("exams","الاختبارات");if(id==="results")results();if(id==="notifications"){await showNotifications("student",user);updateBadge("student",user)}if(id==="messages")messages()}
function home(){content.innerHTML=panel("مرحباً "+user.name,`المرحلة: ${user.stage}`)+`<div class="stats"><div class="stat"><h3>المواد المقبولة</h3><strong>${A.acceptedSubjects(user).length}</strong></div><div class="stat"><h3>الإشعارات</h3><strong>${A.unreadCount("student",user)}</strong></div></div>`}
function subjects(){let accepted=A.acceptedSubjects(user).map(s=>s.code);let subs=A.subjects(user.stage);content.innerHTML=panel("موادي الدراسية","لا يظهر كود المادة للطالب. الطالب يرسل طلباً والمدرس يوافق.")+`<div class="card-grid">${subs.map(s=>card(s.name,`<p>${s.teacher||"بانتظار مدرس"}</p><span class="chip">${accepted.includes(s.code)?"مقبول":"غير مقبول"}</span>`,accepted.includes(s.code)?`<button class="green">مفتوحة</button>`:`<button onclick="req('${s.id}')">إرسال طلب</button>`)).join("")||'<div class="empty">لا توجد مواد لهذه المرحلة</div>'}</div>`}
window.req=async idv=>{let sub=A.getData("subjects").find(s=>s.id===idv);await A.requestSubject(user,sub);alert("تم إرسال الطلب للمدرس");subjects()}
function allowedCodes(){return A.acceptedSubjects(user).map(s=>s.code)}
function showBy(k,title){let codes=allowedCodes();let arr=A.getData(k).filter(x=>codes.includes(x.subjectCode)&&x.status!=="مخفي");content.innerHTML=panel(title)+`<div class="card-grid">${arr.map(x=>card(x.title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<p class="muted">${x.subject}</p>`)).join("")||'<div class="empty">لا توجد بيانات</div>'}</div>`}
function results(){let arr=A.getData("finalResults").filter(r=>r.studentId===user.id||A.code(r.studentCode)===A.code(user.code)||A.eq(r.studentName,user.name));content.innerHTML=panel("النتائج")+`<div class="card-grid">${arr.map(r=>card(r.subject||"نتيجة",`<strong>${r.score||r.grade}</strong>`)).join("")||'<div class="empty">لا توجد نتائج</div>'}</div>`}
function messages(){content.innerHTML=panel("الرسائل")+`<button class="green" onclick="send()">إرسال رسالة</button>`}
window.send=async()=>{let body=prompt("اكتب الرسالة");if(body)await A.addItem("messages",{from:user.name,to:"admin",title:"رسالة طالب",body,studentId:user.id,studentName:user.name,createdAt:A.now()})}
A.onSync(()=>openSection(current));openSection("home");
