
import * as A from "./core.js";import {guard,shell,panel,card,formModal,showNotifications,updateBadge,statBox} from "./dashboard.js";
const user=guard("teacher");const nav=[{id:"home",title:"الرئيسية",icon:"🏠"},{id:"requests",title:"طلبات المادة",icon:"✅"},{id:"lessons",title:"الدروس",icon:"📄"},{id:"assignments",title:"الواجبات",icon:"📝"},{id:"submissions",title:"تصحيح الواجبات",icon:"📥"},{id:"exams",title:"الاختبارات",icon:"🧪"},{id:"manualExams",title:"تصحيح الاختبارات",icon:"✍️"},{id:"attendance",title:"الحضور",icon:"📅"},{id:"students",title:"طلابي",icon:"🎓"},{id:"notifications",title:"الإشعارات",icon:"🔔"},{id:"messages",title:"الرسائل",icon:"✉️"}];let draw=shell("لوحة المدرس v11","teacher",user,nav),current="home";
window.openSection=async id=>{current=id;draw(id);updateBadge("teacher",user);if(id==="home")home();if(id==="requests")requests();if(id==="lessons")items("lessons","الدروس");if(id==="assignments")assignments();if(id==="submissions")submissions();if(id==="exams")exams();if(id==="manualExams")manualExams();if(id==="attendance")attendance();if(id==="students")students();if(id==="notifications"){await showNotifications("teacher",user);updateBadge("teacher",user)}if(id==="messages")messages()}
function myStudents(){let ids=A.getData("subjectRequests").filter(r=>A.code(r.subjectCode)===A.code(user.subjectCode)&&r.status==="accepted").map(r=>r.studentId);return A.getData("students").filter(s=>ids.includes(s.id))}
function home(){let p=A.teacherProfile(user);content.innerHTML=panel("مرحباً "+user.name,`${user.stage} / ${user.subject}`)+`<div class="stats">${statBox("طلاب المادة",p.students.length)}${statBox("الدروس",p.lessons.length)}${statBox("الواجبات",p.assignments.length)}${statBox("الاختبارات",p.exams.length)}</div>`}
function requests(){let arr=A.getData("subjectRequests").filter(r=>A.eq(r.stage,user.stage)&&A.code(r.subjectCode)===A.code(user.subjectCode));content.innerHTML=panel("موافقات المادة")+`<div class="card-grid">${arr.map(r=>card(r.studentName,`<span class="chip">${r.status}</span><p>${r.reason||""}</p>`,`<button class="green" onclick="decide('${r.id}','accepted')">قبول</button><button class="red" onclick="reject('${r.id}')">رفض</button>`)).join("")||'<div class="empty">لا توجد طلبات</div>'}</div>`}
window.decide=async(id,s)=>{await A.decideSubjectRequest(id,s);requests()};window.reject=async id=>{await A.decideSubjectRequest(id,"rejected",prompt("سبب الرفض")||"");requests()}
function items(k,title){let arr=A.getData(k).filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel(title)+`<button class="green" id="add">إضافة</button><div class="card-grid">${arr.map(x=>card(x.title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<p class="muted">${x.deadline?"الموعد: "+x.deadline:""}</p><span class="chip">${x.status||"منشور"}</span>`,`<button onclick="editLesson('${k}','${x.id}')">تعديل</button><button class="red" onclick="del('${k}','${x.id}')">حذف</button>`)).join("")||'<div class="empty">لا توجد بيانات</div>'}</div>`;add.onclick=()=>editLesson(k)}
window.editLesson=(k,idv)=>{let o=A.getData(k).find(x=>x.id===idv)||{};let fields=[{name:"title",label:"العنوان",required:1},{name:"body",label:"الوصف",type:"textarea"},{name:"pdfUrl",label:"رابط PDF Drive/OneDrive"},{name:"videoUrl",label:"رابط فيديو YouTube/Drive"},{name:"status",label:"الحالة",type:"select",options:["منشور","مخفي"]}];formModal(idv?"تعديل":"إضافة",fields,async d=>{d={...d,teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,createdAt:A.now()};idv?await A.updateItem(k,idv,d):await A.addItem(k,d);await A.notify({target:"students",stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,title:"درس جديد",body:d.title});items(k,k)},o)}
function assignments(){let arr=A.getData("assignments").filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel("الواجبات المتقدمة","الطالب يستطيع إرسال نص أو صورة Base64 أو رابط ملف Drive/OneDrive")+`<button class="green" id="add">إضافة واجب</button><div class="card-grid">${arr.map(x=>card(x.title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<p>الدرجة: ${x.score||""}</p><p class="muted">الموعد: ${x.deadline||""}</p>`,`<button onclick="editAssignment('${x.id}')">تعديل</button><button class="red" onclick="del('assignments','${x.id}')">حذف</button>`)).join("")||'<div class="empty">لا توجد واجبات</div>'}</div>`;add.onclick=()=>editAssignment()}
window.editAssignment=idv=>{let o=A.getData("assignments").find(x=>x.id===idv)||{};let fields=[{name:"title",label:"عنوان الواجب",required:1},{name:"body",label:"وصف الواجب",type:"textarea"},{name:"deadline",label:"آخر موعد"},{name:"score",label:"الدرجة"},{name:"pdfUrl",label:"رابط PDF/ملف شرح"},{name:"videoUrl",label:"رابط فيديو"},{name:"status",label:"الحالة",type:"select",options:["منشور","مخفي"]}];formModal(idv?"تعديل واجب":"إضافة واجب",fields,async d=>{d={...d,teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,createdAt:A.now()};idv?await A.updateItem("assignments",idv,d):await A.addItem("assignments",d);await A.notify({target:"students",stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,title:"واجب جديد",body:d.title});assignments()},o)}
function submissions(){let arr=A.getData("assignmentSubmissions").filter(x=>A.code(x.subjectCode)===A.code(user.subjectCode));content.innerHTML=panel("تصحيح الواجبات")+`<div class="card-grid">${arr.map(s=>card(s.assignmentTitle||"واجب",`<p><b>${s.studentName}</b></p><p>${s.answerText||s.answer||""}</p>${s.imageBase64?`<img class="answer-image" src="${s.imageBase64}">`:""}${s.fileUrl?`<a class="media-link" target="_blank" href="${s.fileUrl}">فتح ملف الطالب</a>`:""}<p class="muted">الحالة: ${s.status||"بانتظار التصحيح"} / الدرجة: ${s.grade||"—"}</p>`,`<button onclick="gradeAssign('${s.id}')">تصحيح</button>`)).join("")||'<div class="empty">لا توجد حلول</div>'}</div>`}
window.gradeAssign=async id=>{let g=prompt("الدرجة");if(g===null)return;let note=prompt("ملاحظة للطالب")||"";await A.gradeAssignmentSubmission(id,g,note);submissions()}
function exams(){let arr=A.getData("exams").filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel("منشئ الاختبارات الاحترافي","يدعم MCQ / صح وخطأ / فراغ / مقالي / رفع ملف")+`<button class="green" onclick="examBuilder()">إنشاء اختبار</button><div class="card-grid">${arr.map(e=>card(e.title,`<p>عدد الأسئلة: ${(e.questions||[]).length}</p><p>المجموع: ${(e.questions||[]).reduce((t,q)=>t+Number(q.score||1),0)}</p><span class="chip">${e.status||"منشور"}</span>`,`<button onclick="examBuilder('${e.id}')">تعديل</button><button onclick="copyExam('${e.id}')">نسخ</button><button class="red" onclick="del('exams','${e.id}')">حذف</button>`)).join("")||'<div class="empty">لا توجد اختبارات</div>'}</div>`}
window.copyExam=async id=>{let e=A.getData("exams").find(x=>x.id===id);await A.addItem("exams",{...e,id:A.id(),title:e.title+" - نسخة"});exams()}
window.examBuilder=idv=>{let e=A.getData("exams").find(x=>x.id===idv)||{title:"اختبار جديد",questions:[],duration:"",status:"منشور"};content.innerHTML=panel("منشئ الاختبار")+`<div class="field"><label>عنوان الاختبار</label><input id="exTitle" value="${e.title||""}"></div><div class="field"><label>مدة الاختبار بالدقائق</label><input id="exDuration" value="${e.duration||""}"></div><div class="builder-toolbar">${Object.entries(A.QUESTION_TYPES).map(([k,v])=>`<button onclick="addQ('${k}')">${v}</button>`).join("")}</div><div id="qArea"></div><button class="primary" onclick="saveExam('${idv||""}')">حفظ الاختبار</button>`;window._questions=JSON.parse(JSON.stringify(e.questions||[]));renderQs()}
window.addQ=type=>{window._questions.push({type,text:"",score:1,options:["","","",""],answer:""});renderQs()}
window.delQ=i=>{window._questions.splice(i,1);renderQs()}
window.renderQs=()=>{qArea.innerHTML=window._questions.map((q,i)=>`<div class="q-builder"><h4>سؤال ${i+1}: ${A.QUESTION_TYPES[q.type]}</h4><div class="q-meta"><input placeholder="نص السؤال" value="${q.text||""}" onchange="_questions[${i}].text=this.value"><input placeholder="الدرجة" value="${q.score||1}" onchange="_questions[${i}].score=this.value"><select onchange="_questions[${i}].type=this.value;renderQs()">${Object.entries(A.QUESTION_TYPES).map(([k,v])=>`<option value="${k}" ${q.type===k?"selected":""}>${v}</option>`).join("")}</select></div>${q.type==="mcq"?`<div class="q-options">${(q.options||["","","",""]).map((o,j)=>`<input placeholder="خيار ${j+1}" value="${o||""}" onchange="_questions[${i}].options[${j}]=this.value">`).join("")}</div><input placeholder="الإجابة الصحيحة" value="${q.answer||""}" onchange="_questions[${i}].answer=this.value">`:q.type==="truefalse"?`<select onchange="_questions[${i}].answer=this.value"><option ${q.answer==="صح"?"selected":""}>صح</option><option ${q.answer==="خطأ"?"selected":""}>خطأ</option></select>`:q.type==="fill"?`<input placeholder="الإجابة الصحيحة" value="${q.answer||""}" onchange="_questions[${i}].answer=this.value">`:`<p class="muted">هذا السؤال يصحح يدوياً من المدرس.</p>`}<button class="red" onclick="delQ(${i})">حذف السؤال</button></div>`).join("")}
window.saveExam=async idv=>{let data={title:exTitle.value,duration:exDuration.value,questions:window._questions,teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,status:"منشور",createdAt:A.now()};idv?await A.updateItem("exams",idv,data):await A.addItem("exams",data);await A.notify({target:"students",stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,title:"اختبار جديد",body:data.title});exams()}
function manualExams(){let arr=A.getData("examAttempts").filter(a=>A.code(a.subjectCode)===A.code(user.subjectCode)&&a.status==="بانتظار التصحيح اليدوي");content.innerHTML=panel("تصحيح الأسئلة المقالية والملفات")+`<div class="card-grid">${arr.map(a=>card(a.examTitle,`<p>${a.studentName}</p><p>الدرجة الحالية: ${a.score}/${a.total}</p><span class="chip">${a.status}</span>`,`<button onclick="correctAttempt('${a.id}')">تصحيح</button>`)).join("")||'<div class="empty">لا توجد اختبارات بانتظار التصحيح</div>'}</div>`}
window.correctAttempt=id=>{let a=A.getData("examAttempts").find(x=>x.id===id);content.innerHTML=panel("تصحيح: "+a.examTitle,`الطالب: ${a.studentName}`)+`<div>${(a.details||[]).map((d,i)=>`<div class="question-box ${d.needsManual?'pending-manual':''}"><b>${d.question}</b><p>إجابة الطالب: ${typeof d.answer==="string"&&d.answer.startsWith("data:image")?`<img class="answer-image" src="${d.answer}">`:d.answer}</p><p>الدرجة العظمى: ${d.maxScore}</p>${d.needsManual?`<div class="manual-grade-form"><input id="g_${i}" placeholder="الدرجة" value="${d.manualScore||""}"><input id="n_${i}" placeholder="ملاحظة" value="${d.teacherNote||""}"><button onclick="saveManual('${id}',${i})">حفظ</button></div>`:`<span class="chip">تلقائي: ${d.autoScore}</span>`}</div>`).join("")}</div><button class="green" onclick="finishAttempt('${id}')">اعتماد التصحيح النهائي</button>`}
window.saveManual=async(id,i)=>{let a=A.getData("examAttempts").find(x=>x.id===id);a.details[i].manualScore=Number(document.getElementById("g_"+i).value||0);a.details[i].teacherNote=document.getElementById("n_"+i).value;await A.updateItem("examAttempts",id,{details:a.details});alert("تم حفظ درجة السؤال")}
window.finishAttempt=async id=>{await A.finalizeAttempt(id);manualExams()}
function attendance(){let arr=A.getData("attendance").filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel("الحضور والغياب")+`<button class="green" onclick="newAttendance()">جلسة حضور</button><div class="card-grid">${arr.map(a=>card(a.title,`<p>${a.date}</p>`,`<button onclick="markAttendance('${a.id}')">تسجيل الطلاب</button>`)).join("")||'<div class="empty">لا توجد جلسات</div>'}</div>`}
window.newAttendance=async()=>{let title=prompt("عنوان الجلسة","محاضرة");if(title)await A.addItem("attendance",{title,date:A.today(),teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode});attendance()}
window.markAttendance=async idv=>{for(const s of myStudents()){let status=confirm(`${s.name} حاضر؟`)?"حاضر":"غائب";await A.addItem("attendanceRecords",{sessionId:idv,studentId:s.id,studentCode:s.code,studentName:s.name,status,subject:user.subject,subjectCode:user.subjectCode,date:A.today()});if(status==="غائب")await A.notify({target:"parents",studentCode:s.code,title:"غياب الطالب",body:`تم تسجيل غياب ${s.name}`})}alert("تم التسجيل")}
function students(){let arr=myStudents();content.innerHTML=panel("طلابي")+`<div class="card-grid">${arr.map(s=>{let p=A.studentProfile(s);return card(s.name,`<p>${s.stage}</p><span class="chip">${p.level}</span><span class="chip">${p.points} نقطة</span>`) }).join("")||'<div class="empty">لا يوجد طلاب مقبولون</div>'}</div>`}
function messages(){let arr=A.getData("messages").filter(m=>m.to===user.name||m.teacherId===user.id);content.innerHTML=panel("صندوق الرسائل")+`<button onclick="sendMsg()">رسالة للإدارة</button><div class="card-grid">${arr.map(m=>card(m.title||"رسالة",`<p>${m.body}</p><p class="muted">من: ${m.from}</p>`)).join("")||'<div class="empty">لا توجد رسائل</div>'}</div>`}
window.sendMsg=async()=>{let body=prompt("الرسالة");if(body)await A.addItem("messages",{from:user.name,to:"admin",title:"رسالة مدرس",body,teacherId:user.id,createdAt:A.now()})}
window.del=async(k,idv)=>{await A.deleteItem(k,idv);openSection(current)}
A.onSync(()=>A.scheduleRender(()=>openSection(current),180));openSection("home");
