
import * as A from "./core.js";import {guard,shell,panel,card,formModal,showNotifications,updateBadge} from "./dashboard.js";
const user=guard("teacher");let nav=[{id:"home",title:"الرئيسية",icon:"🏠"},{id:"requests",title:"طلبات المادة",icon:"✅"},{id:"lessons",title:"الدروس",icon:"📄"},{id:"assignments",title:"الواجبات",icon:"📝"},{id:"exams",title:"الاختبارات",icon:"🧪"},{id:"attendance",title:"الحضور",icon:"📅"},{id:"notifications",title:"الإشعارات",icon:"🔔"},{id:"messages",title:"الرسائل",icon:"✉️"}];let draw=shell("لوحة المدرس","teacher",user,nav);let current="home";
window.openSection=async id=>{current=id;draw(id);updateBadge("teacher",user);if(id==="home")home();if(id==="requests")requests();if(id==="lessons")items("lessons","الدروس");if(id==="assignments")items("assignments","الواجبات");if(id==="exams")items("exams","الاختبارات");if(id==="attendance")items("attendance","الحضور");if(id==="notifications"){await showNotifications("teacher",user);updateBadge("teacher",user)}if(id==="messages")messages()}
function home(){content.innerHTML=panel("مرحباً "+user.name,`${user.stage} / ${user.subject}`)+`<div class="stats"><div class="stat"><h3>طلاب المادة</h3><strong>${A.getData("subjectRequests").filter(r=>r.subjectCode===user.subjectCode&&r.status==="accepted").length}</strong></div><div class="stat"><h3>الدروس</h3><strong>${A.getData("lessons").filter(x=>x.teacherId===user.id).length}</strong></div></div>`}
function requests(){let arr=A.getData("subjectRequests").filter(r=>A.eq(r.stage,user.stage)&&A.code(r.subjectCode)===A.code(user.subjectCode));content.innerHTML=panel("طلبات الانضمام للمادة")+`<div class="card-grid">${arr.map(r=>card(r.studentName,`<span class="chip">${r.status}</span>`,`<button class="green" onclick="decide('${r.id}','accepted')">قبول</button><button class="red" onclick="reject('${r.id}')">رفض</button>`)).join("")||'<div class="empty">لا توجد طلبات</div>'}</div>`}
window.decide=async(id,s)=>{await A.decideSubjectRequest(id,s);requests()};window.reject=async id=>{await A.decideSubjectRequest(id,"rejected",prompt("سبب الرفض")||"");requests()}
function items(k,title){let arr=A.getData(k).filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel(title)+`<button class="green" id="add">إضافة</button><div class="card-grid">${arr.map(x=>card(x.title||title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<span class="chip">${x.status||"منشور"}</span>`,`<button onclick="editItem('${k}','${x.id}')">تعديل</button><button class="red" onclick="del('${k}','${x.id}')">حذف</button>`)).join("")||'<div class="empty">لا توجد بيانات</div>'}</div>`;add.onclick=()=>editItem(k)}
window.editItem=(k,idv)=>{let o=A.getData(k).find(x=>x.id===idv)||{};let fields=[{name:"title",label:"العنوان",required:1},{name:"body",label:"الوصف",type:"textarea"},{name:"pdfUrl",label:"رابط PDF Drive/OneDrive"},{name:"videoUrl",label:"رابط فيديو YouTube/Drive"},{name:"status",label:"الحالة",type:"select",options:["منشور","مخفي"]}];formModal(idv?"تعديل":"إضافة",fields,async d=>{d={...d,teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,createdAt:A.now()};idv?await A.updateItem(k,idv,d):await A.addItem(k,d);await A.notify({target:"students",stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,title:"تحديث جديد",body:`تم إضافة/تحديث ${d.title}`});items(k,k)},o)}
function messages(){let arr=A.getData("messages").filter(m=>m.to===user.name||m.teacherId===user.id);content.innerHTML=panel("الرسائل")+`<div class="card-grid">${arr.map(m=>card(m.title||"رسالة",`<p>${m.body}</p><p class="muted">من: ${m.from}</p>`)).join("")||'<div class="empty">لا توجد رسائل</div>'}</div>`}
window.del=async(k,idv)=>{await A.deleteItem(k,idv);openSection(current)}
A.onSync(()=>openSection(current));openSection("home");
