
import * as A from "./core.js";import {guard,shell,panel,card,formModal,showNotifications,updateBadge,statBox} from "./dashboard.js";
const user=guard("teacher");const nav=[{id:"home",title:"الرئيسية",icon:"🏠"},{id:"requests",title:"طلبات المادة",icon:"✅"},{id:"lessons",title:"الدروس",icon:"📄"},{id:"assignments",title:"الواجبات",icon:"📝"},{id:"submissions",title:"حلول الواجب",icon:"📥"},{id:"exams",title:"الاختبارات",icon:"🧪"},{id:"attendance",title:"الحضور",icon:"📅"},{id:"students",title:"طلابي",icon:"🎓"},{id:"notifications",title:"الإشعارات",icon:"🔔"},{id:"messages",title:"الرسائل",icon:"✉️"}];let draw=shell("لوحة المدرس v10","teacher",user,nav);let current="home";
window.openSection=async id=>{current=id;draw(id);updateBadge("teacher",user);if(id==="home")home();if(id==="requests")requests();if(["lessons","assignments"].includes(id))items(id,id==="lessons"?"الدروس":"الواجبات");if(id==="submissions")submissions();if(id==="exams")exams();if(id==="attendance")attendance();if(id==="students")students();if(id==="notifications"){await showNotifications("teacher",user);updateBadge("teacher",user)}if(id==="messages")messages()}
function myStudents(){let ids=A.getData("subjectRequests").filter(r=>A.code(r.subjectCode)===A.code(user.subjectCode)&&r.status==="accepted").map(r=>r.studentId);return A.getData("students").filter(s=>ids.includes(s.id))}
function home(){let p=A.teacherProfile(user);content.innerHTML=panel("مرحباً "+user.name,`${user.stage} / ${user.subject}`)+`<div class="stats">${statBox("طلاب المادة",p.students.length)}${statBox("الدروس",p.lessons.length)}${statBox("الواجبات",p.assignments.length)}${statBox("الاختبارات",p.exams.length)}</div>`}
function requests(){let arr=A.getData("subjectRequests").filter(r=>A.eq(r.stage,user.stage)&&A.code(r.subjectCode)===A.code(user.subjectCode));content.innerHTML=panel("موافقات المادة")+`<div class="card-grid">${arr.map(r=>card(r.studentName,`<span class="chip">${r.status}</span><p>${r.reason||""}</p>`,`<button class="green" onclick="decide('${r.id}','accepted')">قبول</button><button class="red" onclick="reject('${r.id}')">رفض</button>`)).join("")||'<div class="empty">لا توجد طلبات</div>'}</div>`}
window.decide=async(id,s)=>{await A.decideSubjectRequest(id,s);requests()};window.reject=async id=>{await A.decideSubjectRequest(id,"rejected",prompt("سبب الرفض")||"");requests()}
function items(k,title){let arr=A.getData(k).filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel(title)+`<button class="green" id="add">إضافة</button><div class="card-grid">${arr.map(x=>card(x.title,`<p>${x.body||""}</p>${A.mediaLinks(x)}<p class="muted">${x.deadline?"الموعد: "+x.deadline:""}</p><span class="chip">${x.status||"منشور"}</span>`,`<button onclick="editItem('${k}','${x.id}')">تعديل</button><button class="red" onclick="del('${k}','${x.id}')">حذف</button>`)).join("")||'<div class="empty">لا توجد بيانات</div>'}</div>`;add.onclick=()=>editItem(k)}
window.editItem=(k,idv)=>{let o=A.getData(k).find(x=>x.id===idv)||{};let fields=[{name:"title",label:"العنوان",required:1},{name:"body",label:"الوصف",type:"textarea"},{name:"deadline",label:"الموعد النهائي"},{name:"score",label:"الدرجة"},{name:"pdfUrl",label:"رابط PDF Drive/OneDrive"},{name:"videoUrl",label:"رابط فيديو YouTube/Drive"},{name:"status",label:"الحالة",type:"select",options:["منشور","مخفي"]}];formModal(idv?"تعديل":"إضافة",fields,async d=>{d={...d,teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,createdAt:A.now()};idv?await A.updateItem(k,idv,d):await A.addItem(k,d);await A.notify({target:"students",stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,title:"تحديث جديد",body:`تم إضافة/تحديث ${d.title}`});items(k,k)},o)}
function exams(){let arr=A.getData("exams").filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel("الاختبارات مع التصحيح التلقائي")+`<button class="green" onclick="editExam()">إنشاء اختبار</button><div class="card-grid">${arr.map(e=>card(e.title,`<p>عدد الأسئلة: ${(e.questions||[]).length}</p><span class="chip">${e.status||"منشور"}</span>`,`<button onclick="editExam('${e.id}')">تعديل</button><button class="red" onclick="del('exams','${e.id}')">حذف</button>`)).join("")||'<div class="empty">لا توجد اختبارات</div>'}</div>`}
window.editExam=idv=>{let o=A.getData("exams").find(x=>x.id===idv)||{questions:[]};let qs=prompt("اكتب الأسئلة بهذا الشكل: السؤال|الإجابة|الدرجة ثم كل سؤال بسطر", (o.questions||[]).map(q=>`${q.text}|${q.answer}|${q.score}`).join("\n"));if(qs===null)return;let questions=qs.split("\n").filter(Boolean).map(l=>{let [text,answer,score]=l.split("|");return {type:"mcq",text,answer,score:Number(score||1)}});let title=prompt("عنوان الاختبار",o.title||"اختبار جديد");let data={title,questions,teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode,status:"منشور",createdAt:A.now()};idv?A.updateItem("exams",idv,data):A.addItem("exams",data);A.notify({target:"students",stage:user.stage,subject:user.subjectCode,title:"اختبار جديد",body:title});exams()}
function attendance(){let arr=A.getData("attendance").filter(x=>x.teacherId===user.id||A.eq(x.subject,user.subject));content.innerHTML=panel("الحضور والغياب")+`<button class="green" onclick="newAttendance()">جلسة حضور</button><div class="card-grid">${arr.map(a=>card(a.title,`<p>${a.date}</p>`,`<button onclick="markAttendance('${a.id}')">تسجيل الطلاب</button>`)).join("")||'<div class="empty">لا توجد جلسات</div>'}</div>`}
window.newAttendance=async()=>{let title=prompt("عنوان الجلسة","محاضرة"); if(title)await A.addItem("attendance",{title,date:A.today(),teacherId:user.id,teacherName:user.name,stage:user.stage,subject:user.subject,subjectCode:user.subjectCode});attendance()}
window.markAttendance=async idv=>{for(const s of myStudents()){let status=confirm(`${s.name} حاضر؟`)?"حاضر":"غائب";await A.addItem("attendanceRecords",{sessionId:idv,studentId:s.id,studentCode:s.code,studentName:s.name,status,subject:user.subject,subjectCode:user.subjectCode,date:A.today()});if(status==="غائب")await A.notify({target:"parents",studentCode:s.code,title:"غياب الطالب",body:`تم تسجيل غياب ${s.name}`})}alert("تم التسجيل")}
function submissions(){let arr=A.getData("assignmentSubmissions").filter(x=>A.code(x.subjectCode)===A.code(user.subjectCode));content.innerHTML=panel("حلول الواجبات وتصحيحها")+`<div class="card-grid">${arr.map(s=>card(s.assignmentTitle||"واجب",`<p>${s.studentName}</p><p>${s.answer||""}</p><span class="chip">${s.grade||"غير مصحح"}</span>`,`<button onclick="grade('${s.id}')">تصحيح</button>`)).join("")||'<div class="empty">لا توجد حلول</div>'}</div>`}
window.grade=async id=>{let g=prompt("الدرجة"); if(g!==null){await A.updateItem("assignmentSubmissions",id,{grade:g,status:"مصحح"});submissions()}}
function students(){let arr=myStudents();content.innerHTML=panel("طلابي")+`<div class="card-grid">${arr.map(s=>{let p=A.studentProfile(s);return card(s.name,`<p>${s.stage}</p><span class="chip">${p.level}</span><span class="chip">${p.points} نقطة</span>`) }).join("")||'<div class="empty">لا يوجد طلاب مقبولون</div>'}</div>`}
function messages(){let arr=A.getData("messages").filter(m=>m.to===user.name||m.teacherId===user.id);content.innerHTML=panel("صندوق الرسائل")+`<div class="inbox-tabs"><button onclick="sendMsg()">رسالة للإدارة</button></div><div class="card-grid">${arr.map(m=>card(m.title||"رسالة",`<p>${m.body}</p><p class="muted">من: ${m.from}</p>`)).join("")||'<div class="empty">لا توجد رسائل</div>'}</div>`}
window.sendMsg=async()=>{let body=prompt("الرسالة");if(body)await A.addItem("messages",{from:user.name,to:"admin",title:"رسالة مدرس",body,teacherId:user.id,createdAt:A.now()})}
window.del=async(k,idv)=>{await A.deleteItem(k,idv);openSection(current)}
A.onSync(()=>openSection(current));openSection("home");
